export const path = {
    CHOME: '/',
    CSIGNIN: '/dang-nhap',
    CSIGNUP: '/dang-ky',
    CJOB: '/danh-sach-cong-viec',
    CBUSINESS: '/danh-sach-doanh-nghiep',
    CDETAILJOB: '/chi-tiet-cong-viec/:nameJob',
    CDETAILBUSINESS: '/chi-tiet-doanh-nghiep/:nameBusiness',
    CAPPLY: '/ung-tuyen/:nameJobApply',
    CINFOR: '/thong-tin-ca-nhan/:id',
    CMYCV: '/cv-cua-toi',
    CMYJOB: '/cong-viec-cua-toi/:id',

    BSIGNIN: '/doanh-nghiep/dang-nhap',
    BSIGNUP: '/doanh-nghiep/dang-ky',
    BHOME: '/doanh-nghiep/',
    BJOB: '/doanh-nghiep/quan-ly-bai-dang',
    BCANDIDATE: '/doanh-nghiep/quan-ly-ung-vien',
    BPOST: '/doanh-nghiep/dang-tin',
    BINFOR: '/doanh-nghiep/thong-tin-doanh-nghiep/:id',
};
